export const products = [
  {
    title: "Etanol",
    price: 15000,
    stock: 120,
    description: "bidon de 10 lts",
    category: "combustible",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713594624/Sin_t%C3%ADtulo_qspuds.png",
  },

  {
    title: "Remera",
    price: 12000,
    stock: 127,
    description: "unisex talle S, M, L y XL",
    category: "indumentaria",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713562683/remera_m8zhtz.jpg",
  },
  {
    title: "Porta llaves",
    price: 3000,
    stock: 118,
    description: "colgante",
    category: "accesorios",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713561873/20240419_182106_xmdahz.jpg",
  },
  {
    title: "Llavero",
    price: 1000,
    stock: 100,
    description: "llavero de goma",
    category: "accesorios",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713562466/llaveros_i99maz.jpg",
  },
  {
    title: "Bandera",
    price: 3000,
    stock: 105,
    description: "de 50 x 40 cm",
    category: "accesorios",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713562411/bandera_cghtls.jpg",
  },
  {
    title: "Calcos",
    price: 200,
    stock: 1000,
    description: "de corte",
    category: "accesorios",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713562447/calcos_zqhdw6.jpg",
  },
];
