export const products = [
  {
    id: 1,
    title: "Metanol",
    price: 15000,
    stock: 123,
    Description: "bidon de 10 lts",
    category: "combustible",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713594624/Sin_t%C3%ADtulo_qspuds.png",
  },
  {
    id: 2,
    title: "Etanol",
    price: 15000,
    stock: 120,
    Description: "bidon de 10 lts",
    category: "combustible",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713594624/Sin_t%C3%ADtulo_qspuds.png",
  },
  {
    id: 3,
    title: "Buzo",
    price: 18000,
    stock: 125,
    Description: "unisex talle S, M, L y XL",
    category: "indumentaria",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713562425/buzoprovisorio_ktoitu.jpg",
  },
  {
    id: 4,
    title: "Remera",
    price: 12000,
    stock: 127,
    Description: "unisex talle S, M, L y XL",
    category: "indumentaria",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713562683/remera_m8zhtz.jpg",
  },
  {
    id: 5,
    title: "Porta llaves",
    price: 3000,
    stock: 118,
    Description: "colgante",
    category: "accesorios",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713561873/20240419_182106_xmdahz.jpg",
  },
  {
    id: 6,
    title: "Llavero",
    price: 1000,
    stock: 100,
    Description: "llavero de goma",
    category: "accesorios",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713562466/llaveros_i99maz.jpg",
  },
  {
    id: 7,
    title: "Bandera",
    price: 3000,
    stock: 105,
    Description: "de 50 x 40 cm",
    category: "accesorios",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713562411/bandera_cghtls.jpg",
  },
  {
    id: 8,
    title: "Calcos",
    price: 200,
    stock: 1000,
    Description: "de corte",
    category: "accesorios",
    img: "https://res.cloudinary.com/dlncnaofj/image/upload/v1713562447/calcos_zqhdw6.jpg",
  },
];
